name: main

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    #   branches:
    #     - "master"
    # pull_request:
    #   branches:
    #     - "master"
jobs:
  buildx:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Metadata version
        id: meta_version
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Metadata id
        id: meta_id
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test

          tags: |
            type=semver,pattern={{version}}

          flavor: |
            latest=false

      - name: Metadata label
        id: meta_label
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test

          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: test1
        run: echo ${{ steps.meta_id.outputs.tags }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Metadata version
      #   id: meta_version
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: |
      #       a12m/angular-test
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=sha

      # - name: Metadata id
      #   id: meta_id
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: |
      #       a12m/angular-test

      #     tags: |
      #       type=semver,pattern={{version}}

      #     flavor: |
      #       latest=false

      # - name: Metadata label
      #   id: meta_label
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: |
      #       a12m/angular-test
      #     tags: |
      #       type=schedule
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=semver,pattern={{major}}
      #       type=sha
    #  -
    #name: Build and push
    #uses: docker/build-push-action@v3
    #with:
    # context: .
    #platforms: linux/amd64,linux/arm64
    #push: true
    #tags: ${{ steps.meta_version.outputs.tags }}
    #labels: ${{ steps.meta_label.outputs.labels }}
