# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Metadata version
        id: meta_version
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Metadata id
        id: meta_id
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test

          tags: |
            type=semver,pattern={{version}}

          flavor: |
            latest=false

      - name: Metadata label
        id: meta_label
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test

          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: test1
        run: echo ${{ steps.meta_id.outputs.tags }}
