name: what

on:
  # push:
  # tags:
  #   - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Metadata version
        id: meta_version
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Metadata id
        id: meta_id
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test

          tags: |
            type=semver,pattern={{version}}

          flavor: |
            latest=false

      - name: Metadata label
        id: meta_label
        uses: docker/metadata-action@v3
        with:
          images: |
            a12m/angular-test

          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Image meta ID
        run: echo ${{ steps.meta_id.outputs.tags }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: a12m
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy
        run: echo kubectl set image deployment/angular-test angular-test=${{ steps.meta_id.outputs.tags }}
